version: "3.9"
services:
  evolution:
    image: atendai/evolution-api-lite:latest
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - evolution_instances:/evolution/instances
    restart: always

volumes:
  evolution_instances:
